name: Deploy to AWS Lambda

on: push

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # 2. Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 22.18.0

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Compile TypeScript -> dist/
      - name: Build project
        run: npm run build

      # 5. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      # 6. Determine function name based on branch
      - name: Set Lambda function name
        id: set-fn
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "function_name=${{ env.LAMBDA_FUNCTION_NAME_MAIN }}" >> $GITHUB_OUTPUT
          else
            echo "function_name=${{ env.LAMBDA_FUNCTION_NAME_DEV }}" >> $GITHUB_OUTPUT
          fi

      # 7. Deploy to AWS Lambda from dist/ to the specified function
      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: ${{ steps.set-fn.outputs.function_name }}
          code-artifacts-dir: dist
          handler: lambda.handler
          runtime: nodejs22.x