name: Deploy to AWS Lambda

on:
  # Automatic triggers on branch pushes
  push:

  # Manual trigger with environment selection
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - main

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # 2. Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 22.18.0

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Compile TypeScript -> dist/
      - name: Build project
        run: npm run build

      # 5. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      # 6. Determine function name based on branch
      - name: Select Lambda function
        id: lambda-name
        run: |
          # 1. Determine the branch or input environment
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            BRANCH="${{ github.event.inputs.environment }}"
          else
            BRANCH="${GITHUB_REF_NAME}"
          fi

          echo "Detected branch/environment: $BRANCH"

          # 2. Map branch to correct Lambda function name
          if [[ "$BRANCH" == "main" ]]; then
            LAMBDA_FUNCTION="${{ secrets.LAMBDA_FUNCTION_NAME_MAIN }}"
          else
            LAMBDA_FUNCTION="${{ secrets.LAMBDA_FUNCTION_NAME_DEV }}"
          fi

          echo "Using Lambda function: $LAMBDA_FUNCTION"

          # 3. Export output for later steps
          echo "lambda_name=$LAMBDA_FUNCTION" >> $GITHUB_OUTPUT


      # 7. Deploy to AWS Lambda from dist/ to the specified function
      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: ${{ steps.lambda-name.outputs.lambda_name }}
          code-artifacts-dir: dist
          handler: lambda.handler
          runtime: nodejs22.x